In [33]:
import pandas as pd
import numpy as np

#read in data using pandas
train_df = pd.read_csv(r"C:\Users\new\Desktop\dataset\Clinical_Information\main.csv")
#check data has been read in properly
train_df.head()

FILENAME  DEGREEOFSUBTLETLY  NODULESIZE  AGE  XCOOR  YCOOR  DIAGNOSIS
0         1                  5          15   53   1634    692          1
1         2                  5          30   78   1614   1090          1
2         3                  5          30   63   1303    447          0
3         4                  5          14   68    606    836          1
4         5                  5          35   73   1438    692          0

In [34]:
#create a dataframe with all training data except the target column
train_X = train_df.drop(columns=['DIAGNOSIS'])

#check that the target variable has been removed
train_X.head()

FILENAME  DEGREEOFSUBTLETLY  NODULESIZE  AGE  XCOOR  YCOOR
0         1                  5          15   53   1634    692
1         2                  5          30   78   1614   1090
2         3                  5          30   63   1303    447
3         4                  5          14   68    606    836
4         5                  5          35   73   1438    692

In [35]:
#create a dataframe with only the target column
train_y = train_df[['DIAGNOSIS']]

#view dataframe
train_y.head()

DIAGNOSIS
0          1
1          1
2          0
3          1
4          0

In [36]:
from keras.models import Sequential
from keras.layers import Dense

In [37]:
model = Sequential()

In [38]:
n_cols = train_X.shape[1]

In [39]:
#add model layers
model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))

In [40]:
#compile model using mse as a measure of model performance
model.compile(optimizer='adam', loss='mean_squared_error')

In [41]:
from keras.callbacks import EarlyStopping


In [42]:
early_stopping_monitor = EarlyStopping(patience=3)

In [43]:
model.fit(train_X, train_y, validation_split=0.2, epochs=30, callbacks=[early_stopping_monitor])

Train on 123 samples, validate on 31 samples
Epoch 1/30
123/123 [==============================] - 0s 3ms/step - loss: 107930.4758 - val_loss: 119332.9844
Epoch 2/30
123/123 [==============================] - 0s 125us/step - loss: 94320.7457 - val_loss: 104770.0781
Epoch 3/30
123/123 [==============================] - 0s 55us/step - loss: 82926.8594 - val_loss: 91163.9219
Epoch 4/30
123/123 [==============================] - 0s 58us/step - loss: 71870.0753 - val_loss: 79082.7656
Epoch 5/30
123/123 [==============================] - 0s 99us/step - loss: 62034.9780 - val_loss: 68529.8594
Epoch 6/30
123/123 [==============================] - 0s 93us/step - loss: 53971.7313 - val_loss: 59165.6133
Epoch 7/30
123/123 [==============================] - 0s 119us/step - loss: 46650.1742 - val_loss: 50990.5938
Epoch 8/30
123/123 [==============================] - 0s 80us/step - loss: 40229.6667 - val_loss: 43838.5664
Epoch 9/30
123/123 [==============================] - 0s 130us/step - loss: 345

In [44]:
test_y_predictions = model.predict(train_X)

In [45]:
test_y_predictions

array([[ -70.6435    ],
       [ -56.17007   ],
       [ -58.490932  ],
       [ -13.044734  ],
       [ -55.74761   ],
       [ -19.57683   ],
       [  -5.870188  ],
       [  -8.556599  ],
       [ -61.52954   ],
       [ -18.723717  ],
       [ -19.651672  ],
       [   9.1288395 ],
       [ -74.07243   ],
       [ -13.531959  ],
       [  -9.069505  ],
       [ -16.967335  ],
       [ -11.588662  ],
       [ -49.715897  ],
       [  -3.4651105 ],
       [  -7.414273  ],
       [ -65.56248   ],
       [ -23.87859   ],
       [  -6.802772  ],
       [  -6.4843802 ],
       [   1.5531048 ],
       [ -10.701195  ],
       [ -10.1141405 ],
       [ -54.116463  ],
       [ -15.015939  ],
       [ -77.227615  ],
       [ -66.21302   ],
       [ -12.069938  ],
       [ -15.29854   ],
       [ -10.450895  ],
       [ -63.547623  ],
       [ -98.7759    ],
       [ -23.90389   ],
       [ -37.562912  ],
       [  -6.099425  ],
       [ -75.86763   ],
       [ -76.36071   ],
       [  -9.096

In [46]:
#training a new model on the same data to show the effect of increasing model capacity

#create model
model_mc = Sequential()


In [47]:
#add model layers
model_mc.add(Dense(200, activation='relu', input_shape=(n_cols,)))
model_mc.add(Dense(200, activation='relu'))
model_mc.add(Dense(200, activation='relu'))
model_mc.add(Dense(1))


In [48]:
#compile model using mse as a measure of model performance
model_mc.compile(optimizer='adam', loss='mean_squared_error')
#train model
model_mc.fit(train_X, train_y, validation_split=0.2, epochs=30, callbacks=[early_stopping_monitor])

Train on 123 samples, validate on 31 samples
Epoch 1/30
123/123 [==============================] - 0s 4ms/step - loss: 3063.8738 - val_loss: 792.9815
Epoch 2/30
123/123 [==============================] - 0s 217us/step - loss: 1438.1959 - val_loss: 166.5289
Epoch 3/30
123/123 [==============================] - 0s 195us/step - loss: 740.6198 - val_loss: 212.2400
Epoch 4/30
123/123 [==============================] - 0s 213us/step - loss: 490.3517 - val_loss: 673.9570
Epoch 5/30
123/123 [==============================] - 0s 214us/step - loss: 226.4610 - val_loss: 554.1185


In [49]:
#read in training data
train_df_2 = pd.read_csv(r"C:\Users\new\Desktop\dataset\Clinical_Information\main.csv")

#view data structure
train_df_2.head()

FILENAME  DEGREEOFSUBTLETLY  NODULESIZE  AGE  XCOOR  YCOOR  DIAGNOSIS
0         1                  5          15   53   1634    692          1
1         2                  5          30   78   1614   1090          1
2         3                  5          30   63   1303    447          0
3         4                  5          14   68    606    836          1
4         5                  5          35   73   1438    692          0

In [50]:
#create a dataframe with all training data except the target column
train_X_2 = train_df_2.drop(columns=['DIAGNOSIS'])

#check that the target variable has been removed
train_X_2.head()

FILENAME  DEGREEOFSUBTLETLY  NODULESIZE  AGE  XCOOR  YCOOR
0         1                  5          15   53   1634    692
1         2                  5          30   78   1614   1090
2         3                  5          30   63   1303    447
3         4                  5          14   68    606    836
4         5                  5          35   73   1438    692

In [51]:
from keras.utils import to_categorical
#one-hot encode target column
train_y_2 = to_categorical(train_df_2.DIAGNOSIS)

#vcheck that target column has been converted
train_y_2[0:5]

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [52]:
#create model
model_2 = Sequential()


In [53]:
#get number of columns in training data
n_cols_2 = train_X_2.shape[1]


In [54]:
#add layers to model
model_2.add(Dense(250, activation='relu', input_shape=(n_cols_2,)))
model_2.add(Dense(250, activation='relu'))
model_2.add(Dense(250, activation='relu'))
model_2.add(Dense(2, activation='softmax'))

In [55]:
#compile model using accuracy to measure model performance
model_2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [56]:
#train model
model_2.fit(train_X_2, train_y_2, epochs=30, validation_split=0.4, callbacks=[early_stopping_monitor])


Train on 92 samples, validate on 62 samples
Epoch 1/30
92/92 [==============================] - 1s 6ms/step - loss: 3.6882 - acc: 0.7500 - val_loss: 3.6396 - val_acc: 0.7742
Epoch 2/30
92/92 [==============================] - 0s 318us/step - loss: 3.1535 - acc: 0.8043 - val_loss: 3.6396 - val_acc: 0.7742
Epoch 3/30
92/92 [==============================] - 0s 207us/step - loss: 3.1535 - acc: 0.8043 - val_loss: 3.6396 - val_acc: 0.7742
Epoch 4/30
92/92 [==============================] - 0s 200us/step - loss: 3.1535 - acc: 0.8043 - val_loss: 3.6396 - val_acc: 0.7742


In [63]:
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model

x_train, x_test, y_train, y_test = train_test_split(train_X,train_y)

In [64]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

115
39
115
39


In [65]:
y_train

array([[1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [66]:
y_test

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1]], dtype=int64)