In [132]:
import pandas as pd
import numpy as np

#read in data using pandas
train_df = pd.read_csv(r"C:\Users\new\Desktop\dataset\Clinical_Information\main1.csv")
#check data has been read in properly
train_df.head()

FILENAME  DEGREEOFSUBTLETLY  NODULESIZE  AGE  XCOOR  YCOOR  DIAGNOSIS
0         1                  5          15   53   1634    692          1
1         2                  5          30   78   1614   1090          1
2         3                  5          30   63   1303    447          1
3         4                  5          14   68    606    836          1
4         5                  5          35   73   1438    692          0

In [109]:
#create a dataframe with all training data except the target column
train_X = train_df.drop(columns=['DIAGNOSIS'])

#check that the target variable has been removed
train_X.head()

FILENAME  DEGREEOFSUBTLETLY  NODULESIZE  AGE  XCOOR  YCOOR
0         1                  5          15   53   1634    692
1         2                  5          30   78   1614   1090
2         3                  5          30   63   1303    447
3         4                  5          14   68    606    836
4         5                  5          35   73   1438    692

In [110]:
#create a dataframe with only the target column
train_y = train_df[['DIAGNOSIS']]

#view dataframe
train_y.head()

DIAGNOSIS
0          1
1          1
2          1
3          1
4          0

In [111]:
from keras.models import Sequential
from keras.layers import Dense

In [112]:
model = Sequential()

In [113]:
n_cols = train_X.shape[1]

In [114]:
#add model layers
model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))

In [115]:
#compile model using mse as a measure of model performance
model.compile(optimizer='adam', loss='mean_squared_error')

In [116]:
from keras.callbacks import EarlyStopping

In [117]:
early_stopping_monitor = EarlyStopping(patience=3)

In [118]:
model.fit(train_X, train_y, validation_split=0.2, epochs=30, callbacks=[early_stopping_monitor])

Train on 123 samples, validate on 31 samples
Epoch 1/30
123/123 [==============================] - 1s 10ms/step - loss: 82699.1030 - val_loss: 77794.3047
Epoch 2/30
123/123 [==============================] - 0s 83us/step - loss: 66785.3167 - val_loss: 60202.4766
Epoch 3/30
123/123 [==============================] - 0s 89us/step - loss: 51488.3483 - val_loss: 45259.8984
Epoch 4/30
123/123 [==============================] - 0s 98us/step - loss: 39603.2730 - val_loss: 32921.9492
Epoch 5/30
123/123 [==============================] - 0s 209us/step - loss: 29264.0067 - val_loss: 23358.6855
Epoch 6/30
123/123 [==============================] - 0s 98us/step - loss: 21088.1220 - val_loss: 16125.8018
Epoch 7/30
123/123 [==============================] - 0s 163us/step - loss: 14662.2815 - val_loss: 10727.3828
Epoch 8/30
123/123 [==============================] - 0s 98us/step - loss: 9906.9156 - val_loss: 6793.0771
Epoch 9/30
123/123 [==============================] - 0s 98us/step - loss: 6420.936

In [119]:
test_y_predictions = model.predict(train_X)

In [120]:
test_y_predictions

array([[ -4.7831545 ],
       [-28.310059  ],
       [  9.898921  ],
       [ 11.7156    ],
       [-15.990628  ],
       [-14.603345  ],
       [  9.158343  ],
       [ 19.494404  ],
       [-33.281322  ],
       [ -5.743782  ],
       [-16.087723  ],
       [ 24.998135  ],
       [ 24.367062  ],
       [  5.295827  ],
       [ 14.374789  ],
       [  3.3532953 ],
       [  2.2449036 ],
       [ 14.661691  ],
       [ 16.256115  ],
       [ 16.394436  ],
       [-14.502856  ],
       [-21.957047  ],
       [ 19.599087  ],
       [ 20.418903  ],
       [ 31.925564  ],
       [ -1.3241954 ],
       [  3.7505438 ],
       [-25.635105  ],
       [  4.6551147 ],
       [ 22.58688   ],
       [  7.74158   ],
       [  4.2121744 ],
       [ -1.61203   ],
       [ -2.4482832 ],
       [-31.08786   ],
       [ 28.173435  ],
       [-14.515503  ],
       [  7.329047  ],
       [ 13.478297  ],
       [ 15.494258  ],
       [  3.4599943 ],
       [  8.185924  ],
       [  7.0217466 ],
       [  3

In [121]:
#training a new model on the same data to show the effect of increasing model capacity

#create model
model_mc = Sequential()

In [122]:
#add model layers
model_mc.add(Dense(200, activation='relu', input_shape=(n_cols,)))
model_mc.add(Dense(200, activation='relu'))
model_mc.add(Dense(200, activation='relu'))
model_mc.add(Dense(1))

In [123]:
#compile model using mse as a measure of model performance
model_mc.compile(optimizer='adam', loss='mean_squared_error')
#train model
model_mc.fit(train_X, train_y, validation_split=0.2, epochs=30, callbacks=[early_stopping_monitor])

Train on 123 samples, validate on 31 samples
Epoch 1/30
123/123 [==============================] - 1s 7ms/step - loss: 4514.0153 - val_loss: 6141.5283
Epoch 2/30
123/123 [==============================] - 0s 195us/step - loss: 3484.5550 - val_loss: 1217.4542
Epoch 3/30
123/123 [==============================] - ETA: 0s - loss: 861.364 - 0s 259us/step - loss: 1844.9152 - val_loss: 491.5121
Epoch 4/30
123/123 [==============================] - 0s 281us/step - loss: 464.6380 - val_loss: 1154.1927
Epoch 5/30
123/123 [==============================] - 0s 283us/step - loss: 600.9230 - val_loss: 161.9258
Epoch 6/30
123/123 [==============================] - 0s 177us/step - loss: 276.6226 - val_loss: 525.0847
Epoch 7/30
123/123 [==============================] - 0s 302us/step - loss: 135.3916 - val_loss: 104.1951
Epoch 8/30
123/123 [==============================] - 0s 274us/step - loss: 210.5464 - val_loss: 51.1301
Epoch 9/30
123/123 [==============================] - 0s 266us/step - loss: 33

In [124]:
#read in training data
train_df_2 = pd.read_csv(r"C:\Users\new\Desktop\dataset\Clinical_Information\main1.csv")

#view data structure
train_df_2.head()

FILENAME  DEGREEOFSUBTLETLY  NODULESIZE  AGE  XCOOR  YCOOR  DIAGNOSIS
0         1                  5          15   53   1634    692          1
1         2                  5          30   78   1614   1090          1
2         3                  5          30   63   1303    447          1
3         4                  5          14   68    606    836          1
4         5                  5          35   73   1438    692          0

In [125]:
#create a dataframe with all training data except the target column
train_X_2 = train_df_2.drop(columns=['DIAGNOSIS'])

#check that the target variable has been removed
train_X_2.head()

FILENAME  DEGREEOFSUBTLETLY  NODULESIZE  AGE  XCOOR  YCOOR
0         1                  5          15   53   1634    692
1         2                  5          30   78   1614   1090
2         3                  5          30   63   1303    447
3         4                  5          14   68    606    836
4         5                  5          35   73   1438    692

In [126]:
from keras.utils import to_categorical
#one-hot encode target column
train_y_2 = to_categorical(train_df_2.DIAGNOSIS)

#vcheck that target column has been converted
train_y_2[0:5]

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)

In [127]:
model_2 = Sequential()


In [128]:
n_cols_2 = train_X_2.shape[1]


In [129]:
#add layers to model
model_2.add(Dense(250, activation='relu', input_shape=(n_cols_2,)))
model_2.add(Dense(250, activation='relu'))
model_2.add(Dense(250, activation='relu'))
model_2.add(Dense(2, activation='softmax'))

In [130]:
#compile model using accuracy to measure model performance
model_2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [131]:
#train model
model_2.fit(train_X_2, train_y_2, epochs=30, validation_split=0.4, callbacks=[early_stopping_monitor])


ValueError: Error when checking target: expected dense_59 to have shape (2,) but got array with shape (4,)

In [76]:
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model

x_train, x_test, y_train, y_test = train_test_split(train_X,train_y)

In [77]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

115
39
115
39


In [78]:
y_train

array([[1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
    

In [79]:
y_test

array([[1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)